import {
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  CreditCard,
  X,
  FileText,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Info,
  LayoutGrid,
  LogOut,
  MapPin,
  MoreVertical,
  Package,
  Pencil,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  Tag,
  Trash2,
} from 'lucide-react-native';

export const icons = {
  home: Home,
  categories: LayoutGrid,
  cart: ShoppingCart,
  shield: Shield,
  chevronDown: ChevronDown,
  location: MapPin,
  chevronRight: ChevronRight,
  trash: Trash2,
  tag: Tag,
  info: Info,
  back: ArrowLeft,
  more: MoreVertical,
  logout: LogOut,
  orders: Package,
  wishlist: Heart,
  payment: CreditCard,
  help: HelpCircle,
  headphones: Headphones,
  fileText: FileText,
  settings: Settings,
  edit: Pencil,
  share: Share2,
  close: X,
} as const;

export type IconName = keyof typeof icons;
